### ISSUE TITLE
Entry constructors

### ISSUE THREAD

**Issue by kzmnbrs** [koykov/entry#1]
Hello,

It's not exactly convenient to construct entries as such:
```go
var e entry.Entry64
e.Encode(lo, hi)
... = e
```

Could you please provide some kind of built-in constructors? Like `entry.New64(lo, hi)`

**Comment by koykov** [comment]
Feature is too small to create new release, thus get it using `master` tag in go.mod file:
```
require github.com/koykov/entry master
```
and apply tidy command afterward.
